VIA_ENABLE = yes
VIAL_ENABLE = yes

# Encoder (VIAL support)
ENCODER_MAP_ENABLE = yes

# Debug
KEYCODE_STRING_ENABLE = yes

# Save memory
LTO_ENABLE = yes
CONSOLE_ENABLE = no
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE  = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
